[build]
  command = "npm run build"
  publish = "out"  # or your framework's output directory

[build.environment]
  GO_VERSION = "1.19"  # Sets Go version for Netlify

# Install Go in Netlify's build environment
[[plugins]]
  package = "@netlify/plugin-go"